# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_codebook_plugin}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steffen Roegner"]
  s.date = %q{2010-04-21}
  s.description = %q{A handy extension to share pieces of code among teams}
  s.email = %q{steffen@sroegner.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/code_documents_controller.rb",
     "app/controllers/codebook_controller.rb",
     "app/helpers/code_documents_helper.rb",
     "app/helpers/codebook_helper.rb",
     "app/models/code_area.rb",
     "app/models/code_category.rb",
     "app/models/code_document.rb",
     "app/models/code_language.rb",
     "app/views/code_documents/_code_document.html.erb",
     "app/views/code_documents/_editor.html.erb",
     "app/views/code_documents/edit.html.erb",
     "app/views/code_documents/index.html.erb",
     "app/views/code_documents/new.html.erb",
     "app/views/code_documents/show.html.erb",
     "app/views/codebook/_code_area.html.erb",
     "app/views/codebook/_code_language.html.erb",
     "app/views/codebook/_menu.html.erb",
     "app/views/codebook/admin.html.erb",
     "app/views/preferences/_codebook_prefs.html.erb",
     "assets/stylesheets/codebook.css",
     "config/locales/de.yml",
     "config/locales/en.yml",
     "config/locales/hu.yml",
     "config/locales/ja.yml",
     "config/routes.rb",
     "db/migrate/001_create_code_documents.rb",
     "db/migrate/002_create_code_categories.rb",
     "features/add_defaults.feature",
     "features/support/env.rb",
     "init.rb",
     "lang/de.yml",
     "lang/en.yml",
     "lang/hu.yml",
     "lang/ja.yml",
     "routes.rb"
  ]
  s.homepage = %q{http://github.com/sroegner/codebook}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Share code snippets and gists in redmine}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

